[package]
name = "libraw-rs"
version = "0.0.1" # remember to update html_root_url
authors = ["Paolo Barbolini <paolo@paolo565.org>"]
description = "LibRaw bindings"
license = "MIT/Apache-2.0"
repository = "https://github.com/paolobarbolini/libraw-rs"
categories = ["multimedia::images", "api-bindings"]
keywords = ["raw"]
readme = "README.md"
edition = "2018"

[dependencies]
libraw-rs-sys = { version = "0.0.1", path = "../libraw-sys" }
